services:
  - type: web
    name: digital-time-capsule
    env: docker
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dspring.profiles.active=production -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://localhost:5432/timecapsule
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres
      - key: JWT_SECRET
        value: "@Siddardha8639527856Capgemini1234567890!@#$1234567890@31$%^&*%^#$@&!%!@"